# Generated by Django 4.2.30 on 2026-06-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('factory', models.CharField(max_length=100)),
                ('line_id', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=100)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('machine_speed', models.FloatField(blank=True, null=True)),
                ('vibration_level', models.FloatField(blank=True, null=True)),
                ('energy_consumption', models.FloatField(blank=True, null=True)),
                ('production_quality_score', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('production_volume', models.FloatField(blank=True, null=True)),
                ('optimal_condition', models.BooleanField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('predicted_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
